# Generated by Django 2.0.2 on 2018-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('knobs_setting', models.TextField(default='')),
                ('throughput', models.FloatField(default=0.0)),
                ('status', models.CharField(default=b'PENDING', max_length=40))
            ],
        ),
        migrations.CreateModel(
            name='KnobCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('default', models.IntegerField()),
                ('setting', models.CharField(max_length=200))
            ],
        ),
    ]
